import { useDispatch, useSelector } from 'react-redux';
import { useAskQuestionMutation } from '../services/siteChatApi';
import { addMessage, setMessages, setAppState } from '../slices/chatSlice';
import { addToast } from '../slices/toastSlice';

/**
 * Custom hook managing chat input submissions, mutation request dispatches,
 * and simulating a smooth streaming typewriter text animation.
 */
export function useChat() {
  const dispatch = useDispatch();
  const sessionId = useSelector((state) => state.chat.sessionId);
  const messages = useSelector((state) => state.chat.messages);
  const appState = useSelector((state) => state.chat.appState);

  const [askQuestionMutation, { isLoading: isTyping }] = useAskQuestionMutation();

  const handleSendMessage = async (text) => {
    if (!text.trim() || isTyping || (appState !== 'ready' && appState !== 'chatting')) return;

    const userMsg = {
      id: `msg-${Date.now()}-user`,
      role: 'user',
      text: text.trim(),
    };

    // Append user message immediately
    const updatedMessagesWithUser = [...messages, userMsg];
    dispatch(setMessages(updatedMessagesWithUser));
    dispatch(setAppState('chatting'));

    try {
      const response = await askQuestionMutation({ sessionId, question: text }).unwrap();
      const answerText = response.answer;
      const sources = response.sources.map((src) => ({
        title: src.title,
        url: src.url,
        score: src.score ?? 0.85,
      }));

      const aiMessageId = `msg-${Date.now()}-ai`;
      
      // Add initial empty AI message shell
      const initialAiMsg = {
        id: aiMessageId,
        role: 'assistant',
        text: '',
        sources,
      };
      
      const currentMessages = [...updatedMessagesWithUser, initialAiMsg];
      dispatch(setMessages(currentMessages));

      // Simulate streaming typewriter effect
      let currentText = '';
      let charIdx = 0;
      const intervalSpeed = 12; // speed in milliseconds per char

      const streamTimer = setInterval(() => {
        if (charIdx < answerText.length) {
          currentText += answerText[charIdx];
          charIdx++;

          // Construct message state with progressive text
          const streamingMessages = [
            ...updatedMessagesWithUser,
            {
              id: aiMessageId,
              role: 'assistant',
              text: currentText,
              sources,
            },
          ];
          dispatch(setMessages(streamingMessages));
        } else {
          clearInterval(streamTimer);
          dispatch(addToast({ message: 'Answer generated by SiteChat AI.', type: 'success' }));
        }
      }, intervalSpeed);
      
    } catch (error) {
      console.error('Failed to get answer:', error);
      dispatch(
        addMessage({
          id: `msg-${Date.now()}-error`,
          role: 'assistant',
          text: 'Failed to retrieve response from Gemini. Please verify your backend server or API key config.',
          sources: [],
        })
      );
      dispatch(addToast({ message: 'Gemini service returned an error.', type: 'error' }));
    } finally {
      dispatch(setAppState('ready'));
    }
  };

  return {
    messages,
    isTyping,
    sendMessage: handleSendMessage,
  };
}
