import { useDispatch, useSelector } from 'react-redux';
import { useRef, useCallback } from 'react';
import { useAskQuestionMutation } from '../services/siteChatApi';
import { setMessages, setAppState } from '../slices/chatSlice';
import { addToast } from '../slices/toastSlice';

const TYPEWRITER_SPEED_MS = 10;

/**
 * Custom hook managing chat message submission, Gemini response streaming,
 * and source citation mapping from the backend RAG pipeline.
 *
 * State machine:
 *   ready      → chatting  (user sends message)
 *   chatting   → ready     (answer fully streamed or error)
 */
export function useChat() {
  const dispatch = useDispatch();
  const sessionId = useSelector((state) => state.chat.sessionId);
  const messages = useSelector((state) => state.chat.messages);
  const appState = useSelector((state) => state.chat.appState);

  // Ref to cancel any in-progress typewriter on unmount
  const timerRef = useRef(null);

  const [askQuestionMutation, { isLoading: isWaitingForBackend }] = useAskQuestionMutation();

  const handleSendMessage = useCallback(async (text) => {
    const trimmed = text.trim();
    if (!trimmed || isWaitingForBackend || (appState !== 'ready' && appState !== 'chatting')) return;

    const userMsg = {
      id: `msg-${Date.now()}-user`,
      role: 'user',
      text: trimmed,
    };

    const messagesWithUser = [...messages, userMsg];
    dispatch(setMessages(messagesWithUser));

    // Enter chatting state ONLY when the backend call is in-flight
    dispatch(setAppState('chatting'));

    try {
      const response = await askQuestionMutation({ sessionId, question: trimmed }).unwrap();

      const answerText = response.answer ?? '';
      const rawSources = response.sources ?? [];

      const sources = rawSources.map((src) => ({
        title: src.pageTitle ?? '',
        url: src.pageUrl ?? '',
        score: src.score ?? 0,
      }));

      const aiMessageId = `msg-${Date.now()}-ai`;
      let currentText = '';
      let charIdx = 0;

      // Typewriter: stream answer char-by-char then commit final message
      await new Promise((resolve) => {
        timerRef.current = setInterval(() => {
          if (charIdx < answerText.length) {
            currentText += answerText[charIdx];
            charIdx++;
            dispatch(
              setMessages([
                ...messagesWithUser,
                { id: aiMessageId, role: 'assistant', text: currentText, sources },
              ])
            );
          } else {
            clearInterval(timerRef.current);
            timerRef.current = null;
            // Commit the fully-streamed message
            dispatch(
              setMessages([
                ...messagesWithUser,
                { id: aiMessageId, role: 'assistant', text: answerText, sources },
              ])
            );
            resolve();
          }
        }, TYPEWRITER_SPEED_MS);
      });

      dispatch(addToast({ message: 'Answer generated by SiteChat AI.', type: 'success' }));
    } catch (error) {
      console.error('[useChat] Request failed:', error);
      if (timerRef.current) {
        clearInterval(timerRef.current);
        timerRef.current = null;
      }
      dispatch(
        setMessages([
          ...messagesWithUser,
          {
            id: `msg-${Date.now()}-error`,
            role: 'assistant',
            text: "Something went wrong while fetching your answer. Please try again.",
            sources: [],
          },
        ])
      );
      dispatch(addToast({ message: 'Failed to get a response from the backend.', type: 'error' }));
    } finally {
      // Always transition back to ready after answer is fully delivered or errored
      dispatch(setAppState('ready'));
    }
  }, [messages, appState, sessionId, isWaitingForBackend, askQuestionMutation, dispatch]);

  return {
    messages,
    isTyping: isWaitingForBackend,
    sendMessage: handleSendMessage,
  };
}
