import { useDispatch, useSelector } from 'react-redux';
import { useAskQuestionMutation } from '../services/siteChatApi';
import { setMessages, setAppState } from '../slices/chatSlice';
import { addToast } from '../slices/toastSlice';

/**
 * Custom hook managing chat input submissions, real backend answer streaming,
 * and source citation mapping from the RAG pipeline response.
 */
export function useChat() {
  const dispatch = useDispatch();
  const sessionId = useSelector((state) => state.chat.sessionId);
  const messages = useSelector((state) => state.chat.messages);
  const appState = useSelector((state) => state.chat.appState);

  const [askQuestionMutation, { isLoading: isTyping }] = useAskQuestionMutation();

  const handleSendMessage = async (text) => {
    if (!text.trim() || isTyping || (appState !== 'ready' && appState !== 'chatting')) return;

    const userMsg = {
      id: `msg-${Date.now()}-user`,
      role: 'user',
      text: text.trim(),
    };

    const messagesWithUser = [...messages, userMsg];
    dispatch(setMessages(messagesWithUser));
    dispatch(setAppState('chatting'));

    try {
      const response = await askQuestionMutation({ sessionId, question: text }).unwrap();

      const answerText = response.answer ?? '';

      // Backend returns { pageTitle, pageUrl, score }
      const rawSources = response.sources ?? [];
      const sources = rawSources.map((src) => ({
        title: src.pageTitle ?? '',
        url: src.pageUrl ?? '',
        score: src.score ?? 0,
      }));

      const aiMessageId = `msg-${Date.now()}-ai`;

      // Typewriter animation — stream the answer char by char
      let currentText = '';
      let charIdx = 0;

      await new Promise((resolve) => {
        const streamTimer = setInterval(() => {
          if (charIdx < answerText.length) {
            currentText += answerText[charIdx];
            charIdx++;

            dispatch(
              setMessages([
                ...messagesWithUser,
                { id: aiMessageId, role: 'assistant', text: currentText, sources },
              ])
            );
          } else {
            clearInterval(streamTimer);
            // Ensure final complete message is committed
            dispatch(
              setMessages([
                ...messagesWithUser,
                { id: aiMessageId, role: 'assistant', text: answerText, sources },
              ])
            );
            dispatch(addToast({ message: 'Answer generated by SiteChat AI.', type: 'success' }));
            resolve();
          }
        }, 10);
      });
    } catch (error) {
      console.error('[useChat] Failed to get answer:', error);
      dispatch(
        setMessages([
          ...messagesWithUser,
          {
            id: `msg-${Date.now()}-error`,
            role: 'assistant',
            text: 'Failed to retrieve a response. Please verify the backend server is running.',
            sources: [],
          },
        ])
      );
      dispatch(addToast({ message: 'Gemini service returned an error.', type: 'error' }));
    } finally {
      dispatch(setAppState('ready'));
    }
  };

  return {
    messages,
    isTyping,
    sendMessage: handleSendMessage,
  };
}
